title: "Rahul's blog"
description: "Rahul's thoughts on data and machine learning"
url: https://dubeyrahul.github.io
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title
theme: minima
