title: "Data ML Blog"
email: rahuldubey.vjti@gmail.com
description: "Rahul's thoughts on data and machine learning"
url: http://dubeyrahul.github.io
highlighter: rouge
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title
theme: minima
# plugins:
#   - jekyll-feed
#   - jekyll-gist
#   - jekyll-octicons
#   - jekyll-github-metadata
#
# # baseurl: ""
#
# titles_from_headings:
#   enabled:     true
#   strip_title: true
#   collections: true
#
# highlighter: rouge
