name: Rahul Dubey, Machine Learning Engineer
title: Rahul Dubey's Blog
markdown: kramdown
kramdown:
  math_engine: katex
  input: GFM
  auto_ids: true
  hard_wrap: false
  syntax_highlighter: rouge
permalink: /blog/:year/:month/:day/:title
theme: minima
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-octicons
  - jekyll-github-metadata

baseurl: ""
url: "http://dubeyrahul.github.io"
email: rahuldubey.vjti@gmail.com

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true

highlighter: rouge
