project:
  type: website
  output-dir: docs

website:
  title: "Rahul Dubey's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: linkedin
        href: https://linkedin.com/in/dubeyrahul
format:
  html:
    theme: lux
    css: styles.css
    toc: true
    toc-location: right
    toc-depth: 6



